### ISSUE TITLE
Abandoned? 

### ISSUE THREAD

**Issue by pinkyplant** [indicozy/sway-dotfiles-script#4]
Hey,
Just checking out your work, absolutely love it. Has the project been abandoned? Seems really cool and useful.
Thanks
James.

**Comment by pinkyplant** [comment]
@indicozy

**Comment by indicozy** [comment]
Hey,
Yes, it was my mini project and it's now abandoned

**Comment by pinkyplant** [comment]
Ah okay, Thanks.
